package ir.danialchoopan.lumalogic.domain.hint

/**
 * Types of gameplay hints generated by the HintEngine.
 */
enum class HintType {
    ROTATE,
    MOVE,
    PATH,
    COLOR,
    GATE,
    GENERAL
}
